export default {
    DEFAULT_DARK_GRAY: '#91908D',
    DEFAULT_LIGHT_GRAY: '#E0DED9',
    DEFAULT_DARK_BLUE: '#19212D',
    DEFAULT_LIGHT_BLUE: '#F4F7FE',
    DEFAULT_BLUE: '#353E54',
    DEFAULT_WHITE: '#FFFFFF',
    DEFAULT_BLACK: '#121A22',



    DEFAULT_DARK_BLACK: '#0C0B10',
    DEFAULT_DARK_BLACK_2: '#19191F',
    DEFAULT_LIGHT_GRAY_2: '#333438',
    DEFAULT_WHITE_2: '#C2ECFF',

    DEFAULT_LIGHT_WHITE: '#F4F7FC',
    DEFAULT_LIGHT_YELLOW: '#FBF4E2',

    DEFAULT_DARK_RED: '#FB6566',
    DEFAULT_LIGHT_RED: '#FFEFF2',
    DEFAULT_LIGHT_RED_2: '#FFE8EC',
    DEFAULT_GREEN: '#00D390',
    DEFAULT_LIGHT_GREEN: '#F3FBF8',
    DEFAULT_LIGHT_GREEN_2: '#DCF4EC',
    DEFAULT_SKY_BLUE: '#0067FF',
    DEFAULT_SKY_LIGHT_BLUE: '#0F56B3',
    DEFAULT_LIGHT_BLUE_2: '#DFE8FB',
}


